"""Generate a traceable draft from registries; intentionally does not invent evidence."""
from __future__ import annotations
import argparse,json,shutil
from pathlib import Path
def main(root:Path)->None:
 r=json.loads((root/"results"/"result_object.json").read_text(encoding="utf-8")); ids=r["solution"]["top50_supplier_ids"]
 paper=root/"paper";paper.mkdir(exist_ok=True); figures=json.loads((paper/"figure-registry.json").read_text(encoding="utf-8"))
 lines=["# 2021C Supplier-Chain Regression Draft","","## Scope","","This evidence-gated draft discloses a decomposed model rather than claiming integrated robust optimization.","","## Q1 ranking","",f"The complete Top-50 supplier list contains {len(ids)} identifiers: [claim:CLAIM_TOP50]","",", ".join(ids),"","![Supplier scores](../figures/fig_supplier_scores.svg)","","## Q2-Q4","",f"The solver status is {r['status']}; the selected supplier count is {r['solution']['supplier_count']}. The result is a baseline and requires further sensitivity, literature, and implementation analysis before a competition-paper claim.","","![Top-50 capacity](../figures/fig_top50_capacity.svg)","","## Reproducibility","","All values originate from the registered result object and official raw attachments."]
 (paper/"main.md").write_text("\n".join(lines)+"\n",encoding="utf-8")
 tex="\\documentclass{article}\n\\usepackage{graphicx}\n\\begin{document}\n\\section*{2021C Supplier-Chain Regression Draft}\nThis is a traceable draft generated by write-model-paper. The full Top-50 list is in the Markdown source and registered evidence.\\end{document}\n"
 (paper/"main.tex").write_text(tex,encoding="utf-8")
 (paper/"paper_generation_report.json").write_text(json.dumps({"status":"DRAFT_GENERATED","claim_bindings":1,"blocked_claims":["competition-paper completeness"],"template":"template/cume-template.tex required for release"},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 (paper/"claim_usage_report.json").write_text(json.dumps({"CLAIM_TOP50":"used"},indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--root",type=Path,required=True);main(p.parse_args().root)
