"""Executable rule-pack integration, validation, and teaching-demo pipeline."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from algorithms.production_guards import (
    preflight_pdf, validate_artifact_registry, validate_figure_registry,
    validate_table_registry, validate_writing,
)
from rule_pack import validate_rule_pack, write_mapping, write_validation_report


ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / "docs" / "reverse_engineering" / "skill_rule_pack_v1"


def _sha256(path: Path) -> str:
    import hashlib
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def validate_pack() -> int:
    reports = ROOT / "reports" / "skill_rule_integration"
    reports.mkdir(parents=True, exist_ok=True)
    result = validate_rule_pack(PACK)
    write_validation_report(result, reports / "00_rule_pack_validation.md")
    write_mapping(
        PACK, reports / "02_rule_mapping.csv", reports / "02_rule_mapping.md",
        ROOT / "config" / "rule_implementation_registry.yaml",
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result["status"] == "pass" else 1


def demo(run_id: str | None = None) -> Path:
    """Generate one honest, self-contained demo from an executed calculation."""
    run_id = run_id or datetime.now(timezone.utc).strftime("demo-%Y%m%dT%H%M%SZ")
    out = ROOT / "artifacts" / "integration_demo" / run_id
    for name in ("inputs", "parsed_problem", "model_plan", "source_code", "execution_logs", "verified_results", "figures", "tables", "paper_source", "validation_report", "pdf_preflight_report"):
        (out / name).mkdir(parents=True, exist_ok=True)
    (out / "inputs" / "problem.json").write_text(json.dumps({"objective": "minimise (x-2)^2", "bounds": [0, 3]}, indent=2) + "\n", encoding="utf-8")
    _write_json(out / "parsed_problem" / "problem_spec.json", {"variables": [{"name": "x", "unit": "dimensionless", "bounds": [0, 3]}], "objective": "(x-2)^2"})
    _write_json(out / "model_plan" / "candidates.json", {"candidates": [{"name": "bounded convex minimisation", "selected": True, "reason": "one-dimensional convex objective with explicit feasible bounds"}]})

    grid = np.linspace(0.0, 3.0, 3001)
    values = (grid - 2.0) ** 2
    index = int(np.argmin(values))
    optimum, objective = float(grid[index]), float(values[index])
    residual = abs(2 * (optimum - 2.0))
    result = {"status": "verified", "variable": "x", "optimum": optimum, "objective": objective, "constraint_residual": residual, "method": "executed NumPy grid minimisation", "source_note": "generated by this run; not supplied by a language model"}
    result_path = out / "verified_results" / "result.json"
    _write_json(result_path, result)
    (out / "execution_logs" / "run.log").write_text(f"command: {sys.executable} scripts/production_pipeline.py demo\nexit_code: 0\ngrid_points: {len(grid)}\n", encoding="utf-8")
    shutil.copy2(__file__, out / "source_code" / "production_pipeline.py")

    plt.figure(figsize=(5.6, 3.4))
    plt.plot(grid, values, color="#1f4e79", label="$(x-2)^2$")
    plt.scatter([optimum], [objective], color="#c00000", zorder=3, label=f"minimum x={optimum:.4f}")
    plt.xlabel("x")
    plt.ylabel("objective")
    plt.legend()
    plt.tight_layout()
    figure_path = out / "figures" / "objective.png"
    plt.savefig(figure_path, dpi=300)
    plt.close()
    table = {"table_id": "T1", "title_position": "above", "vertical_rules": False, "displayed_values": {"x": [f"{optimum:.4f}"], "residual": [f"{residual:.4e}"]}}
    _write_json(out / "tables" / "table_registry.json", [table])

    registry = {"artifacts": [{"path": "verified_results/result.json", "role": "result", "sha256": _sha256(result_path), "verification_status": "verified", "published_values": {"x_optimum": optimum, "objective": objective}}, {"path": "figures/objective.png", "role": "figure", "sha256": _sha256(figure_path), "verification_status": "verified"}]}
    figure_registry = [{"figure_id": "F1", "path": "figures/objective.png", "claim": "The objective reaches its unique grid minimum at x=2.", "evidence_role": "result", "source_artifact": "verified_results/result.json", "caption": "Objective response and minimizer."}]
    issues = validate_artifact_registry(out, registry) + validate_figure_registry(out, figure_registry) + validate_table_registry([table])
    _write_json(out / "validation_report" / "validation.json", {"status": "pass" if not issues else "fail", "issues": [issue.__dict__ for issue in issues]})

    template = (ROOT / "templates" / "paper" / "verified-report.tex.in").read_text(encoding="utf-8")
    tex = template.replace("{{{OPTIMUM}}}", f"{optimum:.4f}").replace("{{{RESIDUAL}}}", f"{residual:.4e}")
    tex_path = out / "paper_source" / "main.tex"
    tex_path.write_text(tex, encoding="utf-8")
    shutil.copy2(figure_path, out / "paper_source" / "objective.png")
    writing_issues = validate_writing(tex)
    if writing_issues:
        _write_json(out / "validation_report" / "writing_warnings.json", [issue.__dict__ for issue in writing_issues])
    compile_run = subprocess.run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main.tex"], cwd=tex_path.parent, text=True, capture_output=True)
    (out / "execution_logs" / "pdflatex.log").write_text(compile_run.stdout + "\n" + compile_run.stderr, encoding="utf-8")
    if compile_run.returncode:
        raise RuntimeError("pdflatex failed; see execution_logs/pdflatex.log")
    pdf = out / "final_pdf.pdf"
    shutil.copy2(tex_path.parent / "main.pdf", pdf)
    preflight = preflight_pdf(pdf)
    _write_json(out / "pdf_preflight_report" / "preflight.json", preflight)
    (out / "pdf_preflight_report" / "preflight.md").write_text(f"# PDF Preflight\n\nStatus: **{preflight['status'].upper()}**\n\nPages: {preflight.get('page_count', 0)}\n\nManual review required: {', '.join(preflight.get('manual_review_required', []))}\n", encoding="utf-8")
    manifest = {"run_id": run_id, "created_at": datetime.now(timezone.utc).isoformat(), "command": [sys.executable, "scripts/production_pipeline.py", "demo"], "validation_status": "pass" if not issues else "fail", "pdf_preflight_status": preflight["status"], "artifacts": [{"path": str(path.relative_to(out)).replace('\\', '/'), "sha256": _sha256(path), "bytes": path.stat().st_size} for path in sorted(out.rglob('*')) if path.is_file()]}
    _write_json(out / "package_manifest.json", manifest)
    # Keep the archive outside its source tree: placing it inside `out` would
    # recursively include the growing archive in itself.
    archive = shutil.make_archive(str(out.parent / f"{run_id}-submission"), "zip", out)
    print(json.dumps({"output": str(out), "pdf": str(pdf), "preflight": preflight["status"], "submission": archive}, ensure_ascii=False))
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("validate-rule-pack")
    demo_cmd = sub.add_parser("demo")
    demo_cmd.add_argument("--run-id")
    args = parser.parse_args()
    if args.command == "validate-rule-pack":
        return validate_pack()
    demo(args.run_id)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
